services:
  product-service:
    build: .
    container_name: spring_product_service
    ports:
      - "8000:8000"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}